
const ADD_TODO = 'ADD_TODO';
const TOGGLE_TODO = 'TOGGLE_TODO';
const DELETE_TODO = 'DELETE_TODO';


const STARWARS_GET_PEOPLE = 'STARWARS_GET_PEOPLE';
const STARWARS_LOADED_PEOPLE = 'STARWARS_LOADED_PEOPLE';
const STARWARS_GET_DETAILS = 'STARWARS_GET_DETAILS';
const STARWARS_LOADED_DETAILS = 'STARWARS_LOADED_DETAILS';
const STARWARS_LOADED_FAIL = 'STARWARS_LOADED_FAIL';

export {
    ADD_TODO,
    TOGGLE_TODO,
    DELETE_TODO,
    STARWARS_GET_PEOPLE,
    STARWARS_LOADED_PEOPLE,
    STARWARS_GET_DETAILS,
    STARWARS_LOADED_DETAILS,
    STARWARS_LOADED_FAIL,
}