

const STARWARS_GET_PEOPLE = 'STARWARS_GET_PEOPLE';
const STARWARS_LOADED_PEOPLE = 'STARWARS_LOADED_PEOPLE';
const STARWARS_GET_DETAILS = 'STARWARS_GET_DETAILS';
const STARWARS_LOADED_DETAILS = 'STARWARS_LOADED_DETAILS';
const STARWARS_LOADED_FAIL = 'STARWARS_LOADED_FAIL';

// webcoket Echo
const WSECHO_SEND_MESSAGE = 'WSECHO_SEND_MESSAGE';
const WSECHO_GET_RESPONSE = 'WSECHO_GET_RESPONSE';


export {
    STARWARS_GET_PEOPLE,
    STARWARS_LOADED_PEOPLE,
    STARWARS_GET_DETAILS,
    STARWARS_LOADED_DETAILS,
    STARWARS_LOADED_FAIL,
    WSECHO_SEND_MESSAGE,
    WSECHO_GET_RESPONSE,
}